name: Deploy JavaDoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish JavaDoc to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: 'javadoc'
          java-version: '22'
          project: 'gradle'
          javadoc-source-folder: 'build/docs/javadoc'
